### ISSUE TITLE
Word2vec negSamplingCostAndGradient has a slight mistake

### ISSUE THREAD

**Issue by s4sarath** [tiagokv/cs224d#1]
Hi tiagokv ,

In your negSamplingCostAndGradient function , you are taking 

selected = [dataset.sampleTokenIdx() for i in range(K)]

Here , you should make a check to ensure that , the dataset.sampleTokenidx() function should not be 
equal to the target word index . 

Because, intuitively negativeSampling increases the probability of having words other than target words away from predicted word , and increases the probability of target word close to predicted word . So , you should modify that to 

selected  = []
while True:
        index = dataset.sampleTokenIdx()
        if index != target:
            selected .append(index)
        if len(selected )>=K:
            break 

Thanks for sharing the code , was so helpful to me . :+1:

**Comment by tiagokv** [comment]
hey @s4sarath , thanks for letting me know, I will fix it as soon as I can.

**Comment by s4sarath** [comment]
Cool ....... Keep post good things ....
